Repository cs3org/reva, pull requests merged in 2022-01, with the labels that each got.

#2396 Ocdav spaces aware
  .drone.star
  changelog/unreleased/ocdav-spaces-aware.md
  internal/grpc/services/gateway/storageprovider.go
  internal/grpc/services/publicstorageprovider/publicstorageprovider.go
  internal/grpc/services/sharesstorageprovider/sharesstorageprovider.go
  internal/grpc/services/sharesstorageprovider/sharesstorageprovider_test.go
  internal/http/services/owncloud/ocdav/copy.go
  internal/http/services/owncloud/ocdav/dav.go
  internal/http/services/owncloud/ocdav/delete.go
  internal/http/services/owncloud/ocdav/get.go
  internal/http/services/owncloud/ocdav/head.go
  internal/http/services/owncloud/ocdav/mkcol.go
  internal/http/services/owncloud/ocdav/move.go
  internal/http/services/owncloud/ocdav/propfind.go
  internal/http/services/owncloud/ocdav/proppatch.go
  internal/http/services/owncloud/ocdav/publicfile.go
  internal/http/services/owncloud/ocdav/put.go
  internal/http/services/owncloud/ocdav/spaces.go
  internal/http/services/owncloud/ocdav/trashbin.go
  internal/http/services/owncloud/ocdav/tus.go
  internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/mocks/GatewayClient.go
  internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/pending.go
  internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go
  internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares_test.go
  internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/user.go
  internal/http/services/owncloud/ocs/handlers/cloud/users/users.go
  pkg/auth/scope/publicshare.go
  pkg/auth/scope/resourceinfo.go
  pkg/storage/registry/spaces/spaces.go
  pkg/storage/utils/decomposedfs/node/node.go
  pkg/storage/utils/decomposedfs/node/permissions.go
  pkg/storage/utils/decomposedfs/spaces.go
  pkg/storage/utils/decomposedfs/tree/tree.go
  tests/integration/grpc/gateway_storageprovider_test.go
  tests/oc-integration-tests/drone/gateway.toml
  tests/oc-integration-tests/local/gateway.toml
Labels: technical debt

#2393 update tus/tusd to version 1.8.0
  changelog/unreleased/enhancement-update-tusd.md
  go.mod
  go.sum
  pkg/storage/fs/owncloudsql/upload.go
  pkg/storage/utils/decomposedfs/upload.go
  pkg/storage/utils/localfs/upload.go
Labels: dependencies, go

#2416 pass complete spaces as json
  changelog/unreleased/pass-complete-spaces-as-json.md
  internal/grpc/services/gateway/ocmshareprovider.go
  internal/grpc/services/gateway/storageprovider.go
  internal/grpc/services/gateway/usershareprovider.go
  internal/grpc/services/sharesstorageprovider/sharesstorageprovider.go
  internal/http/services/owncloud/ocdav/propfind.go
  internal/http/services/owncloud/ocdav/report.go
  internal/http/services/owncloud/ocs/handlers/cloud/users/users.go
  pkg/storage/registry/spaces/spaces.go
  pkg/storage/registry/spaces/spaces_test.go
Labels: bug

#2422 handle space does not exist
  changelog/unreleased/edge-handle-spaces-does-not-exist-case.md
  internal/http/services/owncloud/ocdav/spaces.go
Labels: bug

#2428 remove unused home provider from spaces registry config
  changelog/unreleased/remove-unused-home-provider-config.md
  pkg/storage/registry/spaces/spaces.go
Labels: bug

#2427 fix registry caching
  changelog/unreleased/fix-registry-caching.md
  internal/grpc/services/gateway/storageprovidercache.go
Labels: bug

#2429 make archiver id based
  changelog/unreleased/make-archiver-id-based.md
  internal/http/services/archiver/handler.go
  internal/http/services/archiver/manager/archiver.go
  internal/http/services/archiver/manager/archiver_test.go
  pkg/storage/utils/downloader/downloader.go
  pkg/storage/utils/downloader/mock/downloader_mock.go
  pkg/storage/utils/walker/mock/walker_mock.go
  pkg/storage/utils/walker/walker.go
Labels: bug

#2430 fix aggregated child folder id
  changelog/unreleased/fix-aggregated-child-folder-id.md
  internal/http/services/owncloud/ocdav/propfind.go
Labels: bug

#2433 fix shares provider filter
  changelog/unreleased/fix-shares-provider-filter.md
  internal/grpc/services/sharesstorageprovider/sharesstorageprovider.go
Labels: bug

#2439 ignore handled errors when creating spaces
  changelog/unreleased/ignore-known-erros.md
  internal/grpc/services/storageprovider/storageprovider.go
Labels: feature

#2452 fix create space error message
  changelog/unreleased/fix-create-space-error-msg.md
  internal/grpc/services/storageprovider/storageprovider.go
Labels: bug

#2482 [tests-only] [full-ci] Add end-of-line to expected-failures files
  tests/acceptance/expected-failures-on-OCIS-storage.md
  tests/acceptance/expected-failures-on-S3NG-storage.md
Labels: qa
